name: lovebox
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  json_serializable: ^6.2.0
  json_annotation: ^4.5.0
  mqtt_client: ^9.6.8
  binary: ^3.0.0
  shared_preferences: ^2.0.15
  logger: ^1.1.0

  visibility_aware_state: ^1.0.3
  expandable: ^5.0.1
  modal_bottom_sheet: ^2.0.1
  flutter_native_splash: ^2.2.3+1
  cupertino_icons: ^1.0.5

  image_picker: ^0.8.5+3
  image_cropper: ^3.0.0
  image: ^3.2.0
  dither:
    git:
      url: https://github.com/monoflop/dither-dart.git
      ref: master

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  flutter_lints: ^2.0.1
  flutter_launcher_icons: ^0.10.0

#Dependency is overwritten because image fails to resolve otherwise
dependency_overrides:
  meta: ">=1.7.0"

flutter:
  uses-material-design: true

  assets:
    - assets/images/logo.png
    - assets/images/logo_android.png
    - assets/images/branding.png
    - assets/images/branding_dark.png

  fonts:
    - family: Love
      fonts:
        - asset: assets/fonts/Love.ttf

